jasypt:
  encryptor:
    password: @JASYPT-ENCRYPTOR-PASSWORD@
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
management:
  health:
    mail:
      enabled: false
  server:
    base-path: /actuator
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
server:
  port: 9090
  servlet:
    context-path: /xxl-job-admin
  shutdown: graceful
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 256
    # 每块buffer的空间大小
    buffer-size: 1024
    # 分配堆外内存
    direct-buffers: true
    accesslog:
      enabled: true
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @PROFILE-ACTIVE@
  datasource:
    driver-class-name: @DATASOURCE-DRIVER-CLASS-NAME@
    username: @DATASOURCE-USERNAME@
    password: @DATASOURCE-PASSWORD@
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:@DATASOURCE-PLATFORM@://@DATASOURCE-HOST@:@DATASOURCE-PORT@/@DATASOURCE-DB-XXL-JOB@?@DATASOURCE-PARAM@
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: @MAIL-USERNAME@
    host: smtp.qq.com
    password: @MAIL-PASSWORD@
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: jakarta.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    username: @MAIL-USERNAME@
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: false
xxl:
  job:
    access-token: yRagfkAddGXdTySYTFzhvMguinulMIMSCcXUbljWDhe
    i18n: zh_CN
    intentionalities: 30
    trigger-pool:
      fast:
        max: 200
      slow:
        max: 100

log:
  path: @XXL-JOB-LOG-PATH@