# /*
#  * Copyright (c) 2022-2024 KCloud-Platform-IOT Author or Authors. All Rights Reserved.
#  * <p>
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  * <p>
#  *   http://www.apache.org/licenses/LICENSE-2.0
#  * <p>
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  */
version: '3.8'
services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower-case-table-names=1
    volumes:
      # 请手动授予rw权限，不然无法写入文件
      - ./mysql8/data:/var/lib/mysql
      - ./mysql8/conf/my.cnf:/etc/mysql/my.cnf
      # 请手动授予rw权限，不然无法写入文件
      - ./mysql8/logs:/var/log/mysql
      - ./mysql8/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=laokou123
      - TZ=Asia/Shanghai
    extra_hosts:
      - "mysql.laokou.org:192.168.30.130"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql.laokou.org" ]
      interval: 5s
      timeout: 10s
      retries: 10
    network_mode: bridge
  redis:
    image: redis:7.2.4
    container_name: redis
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis7/conf/redis.conf:/etc/redis/redis.conf
      # 请手动授予rw权限，不然无法写入文件
      - ./redis7/data:/data
    command: redis-server --appendonly yes --requirepass 'laokou123'
    environment:
      - TZ=Asia/Shanghai
    network_mode: bridge
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    tty: true
    ports:
      - '2181:2181'
    environment:
      # 允许匿名登录
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
    privileged: true
    network_mode: bridge
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    tty: true
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.30.130:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.30.130:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - zookeeper
  rocketmq-namesrv:
    image: apache/rocketmq:5.2.0
    container_name: rocketmq-namesrv
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-server -Xmx256m -Xms256m -Xmn128m
      - TZ=Asia/Shanghai
    network_mode: bridge
  rocketmq-broker:
    image: apache/rocketmq:5.2.0
    container_name: rocketmq-broker
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "8081:8081"
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    command: sh mqbroker -n 192.168.30.1:9876 -c /home/rocketmq/conf/broker.conf autoCreateTopicEnable=true
    environment:
      - JAVA_OPT_EXT=-server -Xmx256m -Xms256m -Xmn128m
      - TZ=Asia/Shanghai
    volumes:
      - ./rocketmq5/broker/conf/broker.conf:/home/rocketmq/conf/broker.conf
    network_mode: bridge
    depends_on:
      - rocketmq-namesrv
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # 请手动授予rw权限，不然无法写入文件
      - ./elasticsearch8/data:/usr/share/elasticsearch/data
      - ./elasticsearch8/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch8/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch8/config/certs/elastic-certificates.p12:/usr/share/elasticsearch/config/certs/elastic-certificates.p12
    environment:
      - TZ=Asia/Shanghai
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - ELASTIC_PASSWORD=laokou123
    network_mode: bridge
    ulimits:
      memlock:
        soft: -1
        hard: -1
  laokou-register:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-register:3.2.1
    container_name: laokou-register
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./nacos/logs:/opt
    env_file:
      - env/nacos.env
    extra_hosts:
      - "mysql.laokou.org:192.168.30.130"
    network_mode: bridge
    depends_on:
      mysql:
        condition: service_healthy
  laokou-sentinel:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-sentinel:3.2.1
    container_name: laokou-sentinel
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "8972:8972"
    volumes:
      - ./sentinel/logs:/opt
    env_file:
      - env/sentinel.env
    extra_hosts:
      - "sentinel.laokou.org:192.168.30.130"
    network_mode: bridge
  laokou-monitor:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-monitor:3.2.1
    container_name: laokou-monitor
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - ./monitor/logs:/opt
    env_file:
      - env/monitor.env
    extra_hosts:
      - "monitor.laokou.org:192.168.30.130"
      - "nacos.laokou.org:192.168.30.130"
    depends_on:
      - laokou-register
    network_mode: bridge
  laokou-seata:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-seata:3.2.1
    container_name: laokou-seata
    tty: true
    env_file:
      - env/common.env
      - env/seata.env
    ports:
      - "7091:7091"
      - "8091:8091"
    volumes:
      - ./seata/logs:/opt
    extra_hosts:
      - "mysql.laokou.org:192.168.30.130"
      - "nacos.laokou.org:192.168.30.130"
      - "redis.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    depends_on:
      - laokou-register
    network_mode: bridge
  laokou-xxl-job:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-xxl-job:3.2.1
    container_name: laokou-xxl-job
    tty: true
    env_file:
      - env/xxl-job.env
    ports:
      - "9095:9095"
    volumes:
      - ./xxl-job/logs:/opt
    extra_hosts:
      - "mysql.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
  laokou-gateway:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-gateway:3.2.1
    container_name: laokou-gateway
    tty: true
    env_file:
      - env/common.env
      - env/gateway.env
    ports:
      - "5555:5555"
    volumes:
      - ./gateway/logs:/opt
    extra_hosts:
      - "nacos.laokou.org:192.168.30.130"
      - "kafka.laokou.org:192.168.30.130"
      - "redis.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - laokou-register
  laokou-im:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-im-start:3.2.1
    container_name: laokou-im
    tty: true
    env_file:
      - env/common.env
      - env/im.env
    ports:
      - "10001:10001"
    volumes:
      - ./im/logs:/opt
    extra_hosts:
      - "nacos.laokou.org:192.168.30.130"
      - "kafka.laokou.org:192.168.30.130"
      - "redis.laokou.org:192.168.30.130"
      - "rocketmq.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - laokou-register
  laokou-auth:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-auth-start:3.2.1
    container_name: laokou-auth
    tty: true
    env_file:
      - env/common.env
      - env/auth.env
    ports:
      - "1111:1111"
    volumes:
      - ./auth/logs:/opt
    extra_hosts:
      - "nacos.laokou.org:192.168.30.130"
      - "kafka.laokou.org:192.168.30.130"
      - "redis.laokou.org:192.168.30.130"
      - "mysql.laokou.org:192.168.30.130"
      - "vue.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - laokou-register
      - laokou-admin
  laokou-admin:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-admin-start:3.2.1
    container_name: laokou-admin
    tty: true
    env_file:
      - env/common.env
      - env/admin.env
    ports:
      - "9990:9990"
    volumes:
      - ./admin/logs:/opt
    extra_hosts:
      - "nacos.laokou.org:192.168.30.130"
      - "kafka.laokou.org:192.168.30.130"
      - "redis.laokou.org:192.168.30.130"
      - "mysql.laokou.org:192.168.30.130"
      - "rocketmq.laokou.org:192.168.30.130"
      - "elasticsearch.laokou.org:192.168.30.130"
      - "seata.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - laokou-register
      - laokou-seata
      - elasticsearch
  laokou-logstash:
    image: registry.cn-shenzhen.aliyuncs.com/koushenhai/laokou-logstash-start:3.2.1
    container_name: laokou-logstash
    tty: true
    env_file:
      - env/common.env
      - env/logstash.env
    ports:
      - "10003:10003"
    volumes:
      - ./logstash/logs:/opt
    extra_hosts:
      - "nacos.laokou.org:192.168.30.130"
      - "kafka.laokou.org:192.168.30.130"
      - "elasticsearch.laokou.org:192.168.30.130"
      - "xxl.job.laokou.org:192.168.30.130"
    restart: always
    privileged: true
    network_mode: bridge
    depends_on:
      - laokou-register
      - elasticsearch
  nginx:
    image: nginx:latest
    container_name: nginx
    # 保持容器在没有守护程序的情况下运行
    tty: true
    restart: always
    privileged: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/dist:/usr/share/nginx/dist
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    extra_hosts:
      - "vue.laokou.org:192.168.30.130"
      - "api.laokou.org:192.168.30.130"
      - "nginx.laokou.org:192.168.30.130"
    network_mode: bridge
    depends_on:
      - laokou-admin
